### PR TITLE
Module Blog - Schema.org

### PR DESCRIPTION
**Pull request by xtiger15x**
Add micro data

### CODE REVIEW

**Comment by lumberman** [comment]
@WPCanyon please disregard this commint we pushed here by mistake. Sorry.

**Comment by lumberman** [comment]
@WPCanyon for some reason all the changes we do to our LC fork get's pushed here as well. Most likley I did the initial push wrong? Please, let me know if there is option in your admin to disable it.

**Comment by lumberman** [comment]
@WPCanyon can you please check what settings you have for this problem? I don't want our temporary/dev code to be pushed automatically to your main repo. 

Sorry for this and thank you.

**Comment by livecomposer** [comment]
Hi Vlad,

I can't find anything in the settings about automatically getting pushes from other branches on the main one.

As far as I know the only way for my branch to get commits from yours is if a request was sent from yours to mine.

Ask xtiger15x if he knows what's going on, perhaps he didn't switch back to your branch after he made the previous request about the PHP notices.

Or if perhaps you know where such a setting is let me know and I'll disable it.

**Pull request closed without merging**
